### ISSUE TITLE
What is rf/sf in BulkExecutor

### ISSUE THREAD

**Issue by fraggamuffin** [executors/executors#16] opened 2016-09-08 14:51 UTC
It claims
rf denotes a CopyConstructible function object with one argument whose result type is R,
sf denotes a CopyConstructible function object with one argument whose result type is S,
and in the table, but no explaination of what they are

**Comment by jaredhoberock** [comment] 2016-09-14 23:02
I think this is a duplicate of #7.

**Comment by fraggamuffin** [comment] 2016-09-29 16:41
Should close as #9 tells us what rf ans sf are.

**Comment by jaredhoberock** [comment] 2016-09-29 17:15
Here's the explanation from #9 , copied here for posterity:

> The current wording in the proposal is cryptic about what's going on with the additional parameters to the bulk execute functions. Here's the basic idea.
> 
> Assume we want to return results from multi-agent executor operations, just like we can from single-agent executor operations. Because there are multiple execution agents involved in the bulk task, we need to treat returns a bit differently.
> 
> Suppose we want to create an executor abstracting this sort of `for` loop:
> 
>     std::vector<int> result(n);
>     int shared_by_all_iterations = 0;
>     for(int i = 0; i < n; ++i)
>     {
>       f(i, result, shared_by_all_iterations);
>     }
> 
>     return result;
> 
> This for loop allows `f` to perform side effects on two variables: `result` & `shared_by_all_iterations`. The `result` variable is returned by this function, and the `shared_by_all_iterations` variable is discarded.
> 
> A bulk executor could wrap up this `for` loop in the `bulk_execute()` customization point:
> 
>     template<class Function, class ResultFactory, class SharedFactory>
>     result_of_t<ResultFactory()>
>     bulk_execute(Function f, size_t n,
>                  ResultFactory result_factory,
>                  SharedFactory shared_factory)
>     {
>       auto result = result_factory();
>       auto shared = shared_factory();
> 
>       for(size_t i = 0; i < n; ++i)
>       {
>         f(i, result, shared);
>       }
> 
>       return result;
>     }
> 
> It turns out that "factories" (i.e., just functions that produce some value that will be used as a parameter to some other function) seem to be the most general way to initialize these special parameters. Moreover, each individual executor can customize the physical location of these variables to ensure they may be accessed by execution agents efficiently.

Before closing this issue: is the wording in the paper sufficient, or does it need additional specification to explain what's going on?

**Comment by jaredhoberock** [comment] 2017-11-10 17:54
These parameters have been defined in the meantime.

**Closed by jaredhoberock** 2017-11-10 17:54 UTC
Labels: duplicate, proposed resolution
